import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: 'SAMO-WIKI',
  tagline: 'ToshonHub — fast, clean, live.',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // GitHub Pages canonical URL + base path for a project repo
  // Ex: https://toshon-jennings.github.io/samo-wiki/
  url: 'https://toshon-jennings.github.io',
  baseUrl: '/samo-wiki/',

  // GitHub Pages deployment config (same repo)
  organizationName: 'toshon-jennings', // your GitHub username or org
  projectName: 'samo-wiki',            // this repo's name
  deploymentBranch: 'gh-pages',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  // Enable GitHub-flavored Markdown (tables, task lists, strikethrough, etc.)
  // Docs: https://docusaurus.io/docs/markdown-features/plugins
  
  presets: [
    [
      'classic',
      {
        docs: {
          // Point to your autogenerated sidebar file (JS version)
          sidebarPath: './sidebars.js',
          // Optional: remove/replace editUrl once you have your own edit links
          editUrl:
            'https://github.com/toshon-jennings/samo-wiki/tree/main/',
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          editUrl:
            'https://github.com/toshon-jennings/samo-wiki/tree/main/',
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    navbar: {
      title: 'SAMO-WIKI',
      logo: {
        alt: 'SAMO-WIKI Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          // Match the key exported in sidebars.js:
          // module.exports = { docs: [{ type: 'autogenerated', dirName: '.' }] };
          sidebarId: 'docs',
          position: 'left',
          label: 'Docs',
        },
        {to: '/blog', label: 'Blog', position: 'left'},
        {
          href: 'https://github.com/toshon-jennings/samo-wiki',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [{label: 'Home', to: '/docs/'}],
        },
        {
          title: 'Community',
          items: [
            {label: 'Stack Overflow', href: 'https://stackoverflow.com/questions/tagged/docusaurus'},
            {label: 'Discord', href: 'https://discordapp.com/invite/docusaurus'},
            {label: 'X', href: 'https://x.com/docusaurus'},
          ],
        },
        {
          title: 'More',
          items: [
            {label: 'Blog', to: '/blog'},
            {label: 'GitHub', href: 'https://github.com/toshon-jennings/samo-wiki'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} SAMO-WIKI.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
